### ISSUE TITLE
ERROR: could not fetch ....autocmake/external/__init__.py

### ISSUE THREAD

**Issue by miroi** [coderefinery/autocmake#175] opened 2016-06-21 15:16 UTC
Hi Rado,

please any help how to fix the error in downloading ?

~~~
Saving to: `update.py'

100%[============================================================================================================================>] 9,867       --.-K/s   in 0s      

2016-06-21 17:14:03 (23.4 MB/s) - `update.py' saved [9867/9867]

milias@lxir073.gsi.de:~/Work/qch/software/radial_atomic_ihfscc/RadialAtomicIHFSCC_devel/cmake/.ls
autocmake.cfg  custom/  update.py
milias@lxir073.gsi.de:~/Work/qch/software/radial_atomic_ihfscc/RadialAtomicIHFSCC_devel/cmake/.less update.py 
milias@lxir073.gsi.de:~/Work/qch/software/radial_atomic_ihfscc/RadialAtomicIHFSCC_devel/cmake/.python update.py --self
- fetching example autocmake.yml
- fetching autocmake/configure.py
- fetching autocmake/__init__.py
- fetching autocmake/external/docopt.py
- fetching autocmake/external/__init__.py
ERROR: could not fetch //raw.githubusercontent.com/coderefinery/autocmake/master/autocmake/external/__init__.py
milias@lxir073.gsi.de:~/Work/qch/software/radial_atomic_ihfscc/RadialAtomicIHFSCC_devel/cmake/.python -V
Python 2.7.3
milias@lxir073.gsi.de:~/Work/qch/software/radial_atomic_ihfscc/RadialAtomicIHFSCC_devel/cmake/.uname -a
Linux lxir073 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u5 x86_64 GNU/Linux
milias@lxir073.gsi.de:~/Work/qch/software/radial_atomic_ihfscc/RadialAtomicIHFSCC_devel/cmake/.
~~~

**Comment by bast** [comment] 2016-06-21 19:54
Please try it again. I got it too sometimes. Don't know what the problem is. Perhaps because the file is actually empty. If the problem persist I will look for another solution.

**Comment by miroi** [comment] 2016-06-21 19:55
Hi,

in between, I repeated the download and it worked.

**Comment by bast** [comment] 2016-06-21 19:58
I suspect it is the empty file. I will keep the issue open for a while. Let's see whether it comes back.

**Comment by bast** [comment] 2016-07-14 14:57
I believe this problem is now solved. Closing.

**Closed by bast** 2016-07-14 14:57 UTC
